version: "3.7"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure    
        
  push:
    build:
      context: ./push
    container_name: 'redis-test-push'
    depends_on:
      - redis
    environment:
      - HOST=redis

  pull:
    build:
      context: ./pull
    container_name: 'redis-test-pull'
    depends_on:
      - redis
    environment:
      - HOST=redis